court_data = {
    'Court Name':['Supreme Court',
'High Court (E-court)',
'Delhi High Court',
'Bombay High Court',
'Punjab And Haryana High Court',
'Allahabad High Court',
'Calcutta High Court',
'Gauhati High Court',
'High Court for State of Telangana',
'High Court of Andhra Pradesh',
'High Court of Chhattisgarh',
'High Court of Gujarat',
'High Court of Himachal Pradesh',
'High Court of Jammu and Kashmir',
'High Court of Jharkhand',
 'High Court of Karnataka',
 'High Court of Kerala',
 'High Court of Manipur',
 'High Court of Meghalaya',
 'High Court of Orissa',
 'High Court of Rajasthan',
'High Court of Sikkim',
 'High Court of Tripura',
 'High Court of Uttarakhand',
 'Madras High Court',
 'Patna High Court',
 'MP High Court',
'District Court',
 'Consumer',
 'NCLT',
 'NCLAT',
  'TDSAT',
 'CESTAT',
 'OERC',
 'CAT',
  'APTEL',
 'DRT',
  'Income Tax',
  'Railway Claims Tribunal',
  'National Green Tribunal',
'CGIT',
   'Insolvency and Bankruptcy Board of India (ibbi.gov.in)',
 'Telangana Commercial Court',
   'Central Electricity Regulatory Commission (CERC)',
'Real Estate Regulatory Authority Ranchi Jharkhand (RERA)',
  'SAT'],
    'Court Link':[
"https://main.sci.gov.in/",
"https://hcservices.ecourts.gov.in/hcservices/main.php",
"https://delhihighcourt.nic.in/",
"https://bombayhighcourt.nic.in/index.php",
"https://highcourtchd.gov.in/",
"https://www.allahabadhighcourt.in",
"https://www.calcuttahighcourt.gov.in/",
"https://ghconline.gov.in/",
"https://tshc.gov.in/",
"https://aphc.gov.in/",
"https://highcourt.cg.gov.in/",
"https://gujarathighcourt.nic.in/",
"https://hphighcourt.nic.in/",
"https://jkhighcourt.nic.in/",
"https://jharkhandhighcourt.nic.in/",
"https://karnatakajudiciary.kar.nic.in/",
"https://hckerala.gov.in/",
"https://hcmimphal.nic.in/",
"https://meghalayahighcourt.nic.in/",
"https://www.orissahighcourt.nic.in/",
"https://hcraj.nic.in/hcraj/",
"https://hcs.gov.in/hcs/",
"https://thc.nic.in/",
"https://highcourtofuttarakhand.gov.in/",
"https://www.hcmadras.tn.nic.in/",
"https://patnahighcourt.gov.in/",
"https://mphc.gov.in/",
"https://services.ecourts.gov.in/ecourtindia_v6/",
"https://confonet.nic.in/",
"https://nclt.gov.in/",
"https://nclat.nic.in/",
"https://tdsat.gov.in/Delhi/Delhi.php",
"https://cestat.gov.in/",
"https://www.orierc.org/",
"https://cgat.gov.in/",
"https://aptel.gov.in/",
"https://drt.gov.in/",
"https://itat.gov.in/page/content/Notice-Board",
"https://rct.indianrail.gov.in/",
"https://www.greentribunal.gov.in/",
"https://cgit.labour.gov.in/",
"https://ibbi.gov.in/en",
"https://ts.e-commcourt.gov.in/",
"https://cercind.gov.in/index.html",
"https://jharera.jharkhand.gov.in/",
"https://sat.gov.in/eindex.asp"
],
    'Scrap Type':[
10,
2,
4,
5,
25,
36,
37,
38,
31,
35,
32,
29,
21,
39,
40,
7,
41,
42,
43,
44,
33,
45,
46,
47,
34,
28,
12,
1,
0,
17,
23,
16,
18,
26,
13,
19,
11,
15,
24,
8,
27,
48,
51,
49,
50,
52,
 ],
 'Status':[],
 'Response Code':[],
 'Date and Time':[]
}


