# Generated by Django 4.2.3 on 2023-08-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Court_Name', models.TextField()),
                ('Court_Link', models.TextField()),
                ('Scrap_Type', models.PositiveIntegerField()),
                ('Site_Status', models.TextField()),
                ('Response_Code', models.TextField()),
                ('Date_and_Time', models.TextField()),
            ],
        ),
    ]
